name: 'Azure Login'
description: 'Login to Azure using service principal credentials'
inputs:
  azure-credentials:
    description: 'Azure credentials JSON containing clientId, clientSecret, and tenantId'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Login to Azure
      shell: bash
      run: |
        CLIENT_ID=$(echo '${{ inputs.azure-credentials }}' | jq -r '.clientId')
        CLIENT_SECRET=$(echo '${{ inputs.azure-credentials }}' | jq -r '.clientSecret')
        TENANT_ID=$(echo '${{ inputs.azure-credentials }}' | jq -r '.tenantId')
        echo "Logging in with client ID: $CLIENT_ID"
        az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID"