name: 'Start App Service'
description: 'Start Azure App Service (webapp or functionapp)'
inputs:
  appName:
    description: 'Name of the app service'
    required: true
  resourceGroupName:
    description: 'Resource group containing the app service'
    required: true
  environment:
    description: 'Environment (dev, qa, prod)'
    required: true
  type:
    description: 'Type of the app service (webapp, functionapp)'
    required: true
  azureCredentials:
    description: 'Azure credentials for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v2.3.0
      with:
        creds: ${{ inputs.azureCredentials }}
    
    - name: Start App Service
      uses: azure/CLI@v2.1.0
      with:
        inlineScript: |
          echo "Starting ${{ inputs.type }} ${{ inputs.appName }} in ${{ inputs.resourceGroupName }} (${{ inputs.environment }})"
          if [ "${{ inputs.type }}" == "webapp" ]; then
            az webapp start --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }}
          elif [ "${{ inputs.type }}" == "functionapp" ]; then
            az functionapp start --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }}
          else
            echo "Unsupported app type: ${{ inputs.type }}"
            exit 1
          fi
          echo "App service started successfully"
