name: 'Get App Configuration'
description: 'Get Azure App Service configuration (webapp or functionapp)'
inputs:
  appName:
    description: 'Name of the app service'
    required: true
  resourceGroupName:
    description: 'Resource group containing the app service'
    required: true
  environment:
    description: 'Environment (dev, qa, prod)'
    required: true
  type:
    description: 'Type of the app service (webapp, functionapp)'
    required: true
  azureCredentials:
    description: 'Azure credentials for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v2.3.0
      with:
        creds: ${{ inputs.azureCredentials }}
    
    - name: Get App Configuration
      uses: azure/CLI@v2.1.0
      with:
        inlineScript: |
          echo "Getting configuration for ${{ inputs.type }} ${{ inputs.appName }} in ${{ inputs.resourceGroupName }} (${{ inputs.environment }})"
          timestamp=$(date +%Y%m%d_%H%M%S)
          output_file="${{ inputs.appName }}_config_${timestamp}.json"
          
          if [ "${{ inputs.type }}" == "webapp" ]; then
            az webapp config appsettings list --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }} > "$output_file"
          elif [ "${{ inputs.type }}" == "functionapp" ]; then
            az functionapp config appsettings list --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }} > "$output_file"
          else
            echo "Unsupported app type: ${{ inputs.type }}"
            exit 1
          fi
          
          echo "Configuration successfully retrieved and saved to $output_file"
          echo "Configuration contents:"
          cat "$output_file"