name: 'Build and Push Image to ACR'
description: 'Build Docker image and push to Azure Container Registry'
inputs:
  appName:
    description: 'Name of the app service'
    required: true
  resourceGroupName:
    description: 'Resource group containing the app service'
    required: true
  environment:
    description: 'Environment (dev, qa, prod)'
    required: true
  containerRegistry:
    description: 'Container registry name'
    required: true
  imageRepositoryAndTag:
    description: 'Image repository and tag (format: repo/image:tag)'
    required: true
  dockerFile:
    description: 'Path to the Dockerfile'
    required: true
    default: './Dockerfile'
  azureCredentials:
    description: 'Azure credentials for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v2.3.0
      with:
        creds: ${{ inputs.azureCredentials }}
    
    - name: Build and push to ACR
      run: |
        az acr build --registry ${{ inputs.containerRegistry }} \
                     --image ${{ inputs.imageRepositoryAndTag }} \
                     --file ${{ inputs.dockerFile }} \
                     .
      shell: bash
    
    - name: Verify image in ACR
      run: |
        az acr repository show --name ${{ inputs.containerRegistry }} --image ${{ inputs.imageRepositoryAndTag }}
        echo "Successfully pushed image to ACR: ${{ inputs.containerRegistry }}.azurecr.io/${{ inputs.imageRepositoryAndTag }}"
      shell: bash