name: App Lifecycle Operations

on:
  workflow_call:
    inputs:
      operation:
        description: 'Operation to perform (start, restart, stop)'
        required: true
        type: string
      app-name:
        description: 'Azure App Service name'
        required: true
        type: string
      resource-group-name:
        description: 'Azure resource group name'
        required: true
        type: string
      app-type:
        description: 'Application type (webapp, functionapp)'
        required: true
        type: string
        default: 'webapp'
      environment:
        description: 'Environment (dev, qa, prod)'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  app-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: 556-DevOps/github-integration-templates/.github/actions/azure-login@main
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: App Service Operation
        uses: 556-DevOps/github-integration-templates/.github/actions/app-service-operation@main
        with:
          operation: ${{ inputs.operation }}
          app-name: ${{ inputs.app-name }}
          resource-group-name: ${{ inputs.resource-group-name }}
          app-type: ${{ inputs.app-type }}