name: Container Operations

on:
  workflow_call:
    inputs:
      operation:
        description: 'Operation to perform (build-and-push, change-image)'
        required: true
        type: string
      registry-name:
        description: 'Azure Container Registry name'
        required: true
        type: string
      image-details:
        description: 'Image repository and tag (e.g. "ai/dual-graphs:v1")'
        required: true
        type: string
      app-name:
        description: 'Azure App Service name (for change-image operation)'
        required: false
        type: string
      resource-group-name:
        description: 'Azure resource group name (for change-image operation)'
        required: false
        type: string
      dockerfile-path:
        description: 'Path to Dockerfile (for build-and-push operation)'
        required: false
        type: string
        default: './Dockerfile'
      environment:
        description: 'Environment (dev, qa, prod)'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  container-operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repository (for Dockerfile and context)
        if: inputs.operation == 'build-and-push'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: caller-repo

      - name: Set up Docker Buildx
        if: inputs.operation == 'build-and-push'
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Container Registry Operation
        uses: 556-DevOps/github-integration-templates/.github/actions/container-registry@main
        with:
          operation: ${{ inputs.operation }}
          registry-name: ${{ inputs.registry-name }}
          image-details: ${{ inputs.image-details }}
          app-name: ${{ inputs.app-name }}
          resource-group-name: ${{ inputs.resource-group-name }}
          dockerfile-path: ${{ inputs.dockerfile-path }}